
model: 'cat_v0'
model_dir: 'data/model'
network: 'res'
heads: ''
task: 'pvnet'
gpus: (0, 1, 2, 3)
resume: true

train:
    optim: 'adam'
    lr: 1e-2  
    epoch: 240
    milestones: (40, 80, 120, 160, 200, 220, 240, 260, 280, 300, 320, 340)
    gamma: 0.2
    batch_size: 32
    dataset: 'LinemodTrain'
    cropresize_rate: 1.0
    rotate_rate: 1.0
    rotate_min: -30
    rotate_max: 30
    weight_decay: 0.
    batch_sampler: 'image_size'


test:
    dataset: 'LinemodTest'
    batch_size: 1
    batch_sampler: 'image_size'
